services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped

    # 컨테이너에서 호스트(도커 밖 앱)에 접근하기 위한 설정
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus # Prometheus 데이터 영속화
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=3d"
      - "--storage.tsdb.wal-compression"
      - "--query.max-concurrency=5"

    mem_limit: 300m

    deploy:
      resources:
        limits:
          memory: 300M

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana # grafana 데이터 영속화
    ports:
      - "3000:3000"

    mem_limit: 200m
    deploy:
      resources:
        limits:
          memory: 200M

volumes:
  prometheus_data:
  grafana_data:
