global:
  scrape_interval: 1m
  scrape_timeout: 10s

  external_labels:
    monitor: 'system-monitor'

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "prometheus:9090"
  - job_name: "springboot"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "host.docker.internal:8081"
  - job_name: "mysql"
    static_configs:
      - targets:
          - "mysql-exporter:9104"